version: '3.4'
services:
  ecommerce.api.customers:
    image: '${DOCKER_REGISTRY-}ecommerceapicustomers'
    build:
      context: .
      dockerfile: Ecommerce.Api.Customers/Dockerfile
    networks:
      - blockmyshownet

  ecommerce.api.orders:
    image: '${DOCKER_REGISTRY-}ecommerceapiorders'
    build:
      context: .
      dockerfile: Ecommerce.Api.Orders/Dockerfile
    networks:
      - blockmyshownet

  ecommerce.api.products:
    image: '${DOCKER_REGISTRY-}ecommerceapiproducts'
    build:
      context: .
      dockerfile: Ecommerce.Api.Products/Dockerfile
    networks:
      - blockmyshownet

  ecommerce.api.search:
    image: '${DOCKER_REGISTRY-}ecommerceapisearch'
    build:
      context: .
      dockerfile: Ecommerce.Api.Search/Dockerfile
    networks:
      - blockmyshownet

networks:
  blockmyshownet:
    external:
      name: network-ecommerce