version: '3.4'
services:
  ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '26011:80'
    networks:
      - blockmyshownet

  ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '26012:80'
    networks:
      - blockmyshownet

  ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '26013:80'
    networks:
      - blockmyshownet

  ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Customers=http://ecommerce.api.customers
      - Services__Products=http://ecommerce.api.products
      - Services__Orders=http://ecommerce.api.orders
    ports:
      - '26014:80'
    networks:
      - blockmyshownet

networks:
  blockmyshownet:
    external:
      name: network-ecommerce