version: '3.4'
services:
  customers:
    image: ecommerceshree.azurecr.io/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '80/http'     

  orders:
    image: ecommerceshree.azurecr.io/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '80/http'
    

  products:
    image: ecommerceshree.azurecr.io/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '80/http'    

  search:
    image: ecommerceshree.azurecr.io/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Customers=http://10.0.0.4:19081/lil/customers/
      - Services__Products=http://10.0.0.4:19081/lil/products/
      - Services__Orders=http://10.0.0.4:19081/lil/orders/
    ports:
      - '26014:80'
 